name: .NET
on:
  pull_request:
    branches:
      - master
      - hotfixes/**
  push:
    branches:
      - master
      - hotfixes/**
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !!github.event.pull_request }}
jobs:
  build:
    runs-on: arc-runner
    permissions:
      contents: write
      checks: write
      pull-requests: write
    outputs:
      build-version: ${{ steps.semver.outputs.version }}
      is-release-build: ${{ steps.semver.outputs.is-release-build }}
    steps:
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install curl git -y
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
        env:
          DOTNET_INSTALL_DIR: ./
      - name: SemVer
        id: semver
        uses: BedeGaming/gha-semver@v1
        with:
          default-branch: master
      - name: Run Unit Tests
        run: make -j2 test